### PR TITLE
Selecting Mentors

### PR DESCRIPTION
**Pull request by sajedazoabi**
it takes two mentors id and select everything related to that id

### CODE REVIEW

**Review by Wyrd00 — APPROVED** [review]

**Review by matthewdking — APPROVED** [review]
nice job @sajedazoabi

**Review by Karyum — APPROVED** [review]
# I fucking love you guys for these pull requests :heart:

**Comment by Wyrd00** [comment]
iy toooo <3

**Comment by matthewdking** [comment]
# WE LOVE YOU TOO MARIO :heart:

**Comment by matthewdking** [comment]
# BEST QA EVER

**Comment by sajedazoabi** [comment]
:heart:

**Pull request merged**
