### PR TITLE
fix error in arguments passed in to updateCategoryScore

### PR DESCRIPTION
**Pull request by matthewdking**
relates #26

### CODE REVIEW

**Comment by matthewdking** [comment]
# I LOVE TO MAKE PULL REQUESTS :heart:

**Review by Wyrd00 — APPROVED** [review]

**Comment by Wyrd00** [comment]
# Nerd. 🤓

**Review by sajedazoabi — APPROVED** [review]

**Comment by matthewdking** [comment]
vanilla :icecream:

**Review by Karyum — APPROVED** [review]
# Yo king i need a massage

**Pull request merged**
